# Generated by Django 4.1 on 2022-09-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
    ]
